spawn:
  x: -28
  y: 64
  z: 992
  world: world

minplayer: 5
scoretowin: 10

spawnrate_xp: 5
spawnrate_iron: 5
spawnrate_xp_enable: true
spawnrate_iron_enable: true
spawnlapis: false
spawnlapis_rate: 5

timelimit_enable: true
timelimit_time: 30

chest_breakable: true
friendlyfire: false
eternalday: true

spawnmob: false
mobgriefing: false

healonpoint: true